name: deploy-to-kyma

on:
  workflow_dispatch:

jobs:
  
  deploy-to-kyma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.DEV_KUBECONFIG }}
      # - uses: kwiatekus/setup-kymaCLI@main
      #   with:
      #     version: '2.0.2'
      - name: Install Kyma CLI
        run: | 
          curl -Lo kyma https://storage.googleapis.com/kyma-cli-stable/kyma-linux
          chmod +x kyma
      - name: Run Kyma CLI
        run: |         
          kyma version 
      